In [1]:
# Defining a list
my_list = [1, 2, 3, 4]

# Modifying the list (changing, adding, and removing elements)
my_list[1] = 20    # Changing the second element
my_list.append(5)  # Adding an element
my_list.remove(3)  # Removing an element

print(my_list)  # Output: [1, 20, 4, 5]


[1, 20, 4, 5]


In [9]:
# Defining a tuple
my_tuple = (1, 2, 3, 4)

# Trying to modify the tuple will raise an error
# my_tuple[1] = 20  # Uncommenting this will cause a TypeError

print(my_tuple)  # Output: (1, 2, 3, 4)


(1, 2, 3, 4)


In [3]:
my_list[4]

IndexError: list index out of range

In [13]:
my_tuple[0] = 1

TypeError: 'tuple' object does not support item assignment

In [15]:
print(my_tuple[0])
print(my_list[1])

1
20


In [29]:
print(my_tuple[1:3]) #slicing

(2, 3)


In [76]:
# In python you define objects like strings, tuples ... 
# A tuple of tuples / Nested Tuples 
nested_tuples = (1, (2, 3), (4, 5))
print(nested_tuples)

len(nested_tuples)

(1, (2, 3), (4, 5))


3

In [66]:
my_tuple = (1, 2, 2, 3, 3)
# Two "2" in the tuple 
my_tuple.count(2)

2

In [70]:
# Concatenation. 
my_tuple = (1, 2)
my_tuple2 = (3, 4)
my_final_tuple = my_tuple + my_tuple2
my_final_tuple

(1, 2, 3, 4)

In [94]:
# Mixed Lists 
mixed_list = [1, 'hi', True, 3.14]
print(mixed_list)

# Empty List
empty_list = []
print(empty_list)

# Accessing Lists / Slicing Lists 
mixed_list[:3]
# Modify Lists 


[1, 'hi', True, 3.14]
[]


[1, 'hi', True]

In [118]:
# Demonstrate the dict function 
# Creating a dictionary with dict()
person = dict(name="Alice", age=30, profession="Engineer")

print(person)  
# Output: {'name': 'Alice', 'age': 30, 'profession': 'Engineer'}

my_dict = {
    "name": "Bob",
    "age": 25,
    "is_students": True,
    "grades": [88, 92, 85]
}

print(my_dict)

# Add to a list 
my_dict['hi'] = True

print(my_dict)

# Delete from a lsit 
my_dict.pop('hi')

print(my_dict)

# Edit a list 
my_dict["age"] = 30

my_dict

{'name': 'Alice', 'age': 30, 'profession': 'Engineer'}
{'name': 'Bob', 'age': 25, 'is_students': True, 'grades': [88, 92, 85]}
{'name': 'Bob', 'age': 25, 'is_students': True, 'grades': [88, 92, 85], 'hi': True}
{'name': 'Bob', 'age': 25, 'is_students': True, 'grades': [88, 92, 85]}


{'name': 'Bob', 'age': 30, 'is_students': True, 'grades': [88, 92, 85]}

In [104]:
# Accessing dictionaries 
print(person['name'])
print(person.get('name'))

Alice
Alice


In [122]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4])
print(arr)  # Output: [1 2 3 4]

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]


[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [138]:
# Operations 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

print(a * b)

print(a ** b)


[5 7 9]
[ 4 10 18]
[  1  32 729]


In [142]:
# Create 3 x 2 array 
empty_arr = np.zeros((3, 2))
empty_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [144]:
# Can you find even numbers 

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [num for num in numbers if num % 2 == 0]
print(even_numbers)

# Find even numbers in a list. 

[2, 4, 6, 8, 10]


In [206]:
import numpy as np
all_door_options = (1, 2, 3)
my_door_choice = 1 # 1, 2, 3
i_won = 0
reps = 10000
for i in range(reps):
    secret_winning_door = np.random.choice(all_door_options)
    all_door_options_list = list(all_door_options)
    # Take the secret winning door, so we don't show it as a "goat" losing
    all_door_options_list.remove(secret_winning_door)
    try:
        all_door_options_list.remove(my_door_choice)
    except:
        pass
    # show a "goat" losing door and remove it
    goat_door_reveal = np.random.choice(all_door_options_list)
    all_door_options_list.remove(goat_door_reveal)

    # put secret winning door back in if it wasn't our choice
    # we previously removed it, so it would be shown as a "goat" losing. 
    if secret_winning_door != my_door_choice:
        all_door_options_list.append(secret_winning_door)

    my_door_choice = all_door_options_list[0]

    if my_door_choice == secret_winning_door:
        i_won += 1

i_won / reps * 100

66.3

In [208]:
import numpy as np

def monty_hall_simulation(num_trials=10000, switch=True):
    wins = 0

    for _ in range(num_trials):
        # Randomly assign the car behind one of the three doors
        doors = [0, 1, 2]
        car_door = np.random.choice(doors)
        
        # Player randomly picks one of the doors
        player_choice = np.random.choice(doors)
        
        # Monty opens a door that has a goat (and is not the player's choice)
        remaining_doors = [door for door in doors if door != player_choice and door != car_door]
        monty_opens = np.random.choice(remaining_doors)
        
        # If the player switches, they choose the other remaining door
        if switch:
            player_choice = [door for door in doors if door != player_choice and door != monty_opens][0]
        
        # Check if the player wins (if their final choice is the car door)
        if player_choice == car_door:
            wins += 1
    
    win_percentage = (wins / num_trials) * 100
    return win_percentage

# Run the simulation
num_trials = 10000
switch_win_percentage = monty_hall_simulation(num_trials=num_trials, switch=True)
stay_win_percentage = monty_hall_simulation(num_trials=num_trials, switch=False)

print(f"Winning percentage when switching: {switch_win_percentage:.2f}%")
print(f"Winning percentage when staying: {stay_win_percentage:.2f}%")


Winning percentage when switching: 67.13%
Winning percentage when staying: 33.31%
